# Generated by Django 5.0.7 on 2024-07-26 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок объявления')),
                ('ad_id', models.PositiveIntegerField(unique=True, verbose_name='ID объявления')),
                ('author', models.CharField(max_length=100, verbose_name='Автор объявления')),
                ('views', models.PositiveIntegerField(verbose_name='Количество просмотров')),
                ('position', models.PositiveSmallIntegerField(verbose_name='Позиция объявления')),
            ],
        ),
    ]
